export const chainIcons: Record<string, string> = {
  ethereum: "/assets/chains/ethereum.svg",
  optimism: "/assets/chains/optimism.svg",
  arbitrum: "/assets/chains/arbitrum.svg",
  fraxtal: "/assets/chains/fraxtal.png",
};

export const tokenIcons: Record<string, string> = {
  arb: "/assets/chains/arbitrum.svg",
  asdcrv: "/assets/tokens/asdcrv.png",
  crv: "/assets/tokens/crv.png",
  crvusd: "/assets/tokens/crvusd.png",
  dlcbtc: "/assets/tokens/dlcbtc.png",
  ethfi: "/assets/tokens/ethfi.png",
  fxn: "/assets/tokens/fxn.png",
  fxs: "/assets/tokens/fxs.png",
  ibtc: "/assets/tokens/ibtc.webp",
  pufeth: "/assets/tokens/pufeth.png",
  sdola: "/assets/tokens/sdola.png",
  sfrax: "/assets/tokens/sfrax.png",
  sfrxeth: "/assets/tokens/sfrxeth.png",
  squid: "/assets/tokens/squid.png",
  susde: "/assets/tokens/susde.png",
  stxai: "/assets/tokens/stxai.png",
  tbtc: "/assets/tokens/tbtc.png",
  usde: "/assets/tokens/usde.png",
  "usd0usd0++": "/assets/tokens/usd0usd0++.png",
  uwu: "/assets/tokens/uwu.png",
  wbtc: "/assets/tokens/wbtc.png",
  weth: "/assets/tokens/weth.png",
  wsteth: "/assets/tokens/wsteth.png",
  yneth: "/assets/tokens/yneth.png",
  xaum: "/assets/tokens/xaum.png",
};
